/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MusicEntry {
  'id' : bigint,
  'coverImageUrl' : string,
  'title' : string,
  'album' : string,
  'streamingPlatforms' : Array<StreamingPlatform>,
  'genre' : [] | [string],
  'artist' : string,
  'releaseYear' : bigint,
}
export interface StreamingPlatform { 'url' : string, 'name' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMusicEntry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      [] | [string],
      Array<StreamingPlatform>,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMusicEntry' : ActorMethod<[bigint], undefined>,
  'getAllEntries' : ActorMethod<[], Array<MusicEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIdEntry' : ActorMethod<[bigint], MusicEntry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchEntries' : ActorMethod<[string], Array<MusicEntry>>,
  'updateMusicEntry' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      [] | [string],
      Array<StreamingPlatform>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];