/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StreamingPlatform = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MusicEntry = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'album' : IDL.Text,
  'streamingPlatforms' : IDL.Vec(StreamingPlatform),
  'genre' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
  'releaseYear' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMusicEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Vec(StreamingPlatform),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMusicEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(MusicEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIdEntry' : IDL.Func([IDL.Nat], [MusicEntry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEntries' : IDL.Func([IDL.Text], [IDL.Vec(MusicEntry)], ['query']),
  'updateMusicEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Vec(StreamingPlatform),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StreamingPlatform = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MusicEntry = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'album' : IDL.Text,
    'streamingPlatforms' : IDL.Vec(StreamingPlatform),
    'genre' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
    'releaseYear' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMusicEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Vec(StreamingPlatform),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMusicEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(MusicEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIdEntry' : IDL.Func([IDL.Nat], [MusicEntry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEntries' : IDL.Func([IDL.Text], [IDL.Vec(MusicEntry)], ['query']),
    'updateMusicEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Vec(StreamingPlatform),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };